### ISSUE TITLE
Code quality checklist

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#1225]
This ticket is used to track progressive changes we need to make to the codebase in order to improve the code quality and prevent regression.

```[tasklist]
### Tasks
- [x] eslint: enforce "@typescript-eslint/no-non-null-assertion"
- [x] "strict": true in ALS tsconfig.js file [see](https://stackoverflow.com/a/58868185/99834) (might split it into multi-step)
- [x] eslint: enforce "no-empty-function"
- [x] eslint: enforce "no-case-declarations"
- [x] eslint: enforce "no-constant-condition"
- [x] eslint: enforce "no-control-regex"
- [x] eslint: enforce "no-prototype-builtins"
- [ ] typescript-eslint: adopt [strict-type-checked](https://typescript-eslint.io/users/configs/#strict-type-checked) (keep last)
```

Blocked ones:

- [ ] adopt ESM (due vscode extensions not supporting them yet)
- [x] adopt chai v5 (requires ESM codebase)

AAP-22902
