### ISSUE TITLE
test: console output is polluted with output from lightspeed server

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#1481]
Our console logs when runnings tests is polluted with output from others tools and services that run in parallel, making it harder to debug. We need to address these by ensuring that they end-up in specific log files that are collected.

## output pollution with: test unit

Please note that this pollution happens with passing tests! If this would be visible on screen on failed tests, it would have not being a problem.

Only mocha output should be visible for passing tests.

```
✔ suggestion has no matches
{ contentmatches: [ { contentmatch: [Array] } ] }
YAMLParseError: Unexpected scalar at node end at line 2, column 1:

- name: foo
I
^

    at Composer.onError (/home/runner/work/vscode-ansible/vscode-ansible/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveEnd (/home/runner/work/vscode-ansible/vscode-ansible/node_modules/yaml/dist/compose/resolve-end.js:31:21)
    at Object.composeDoc (/home/runner/work/vscode-ansible/vscode-ansible/node_modules/yaml/dist/compose/compose-doc.js:37:27)
...    ✔ suggest has invalid YAML
```

## lightspeed server pollution with: test ui
```
{"level":"info","message":"{\n  \"playbookGenerationAction\": {\n    \"wizardId\": \"d406325e-dcf8-4741-afe5-0181e6571209\",\n    \"action\": 0,\n    \"toPage\": 1\n  },\n  \"metadata\": {\n    \"ansibleExtensionVersion\": \"0.0.0\"\n  }\n}"}
```

## pollution with: test e2e

Spamming messages such below must go in specific log file, not test console:
```
Ansible found in the workspace
[file-inspection] language set by file inspection
[inline-suggestions] ...
[ansible-lightspeed] ...
```

## Remediation

```[tasklist]
### Tasks
- [ ] test ui: have clean mocha output, other services should log to file
- [ ] test e2e: have clean mocha output, other services should log to file
- [ ] test unit: have clean mocha output, other services should log to file
- [x] test als: no action needed, output seems clean
```
